### ISSUE TITLE
SWF file not being reversed

### ISSUE THREAD

**Issue by ipentest** [cure53/Flashbang#17]
Hey Cure53 Team,

Awesome work! Thanks a ton... My issue is with the specific SWF at https://www.sc.com/sg/personal-banking/investment/online-trading-tour/main.swf

It's not being reversed... Am I missing anything here?

Thanks,
Kiran

**Comment by cure53** [comment]
Heya, maybe the Shumway engine version we employ cannot handle the file. We need to upgrade this but currently have no resources for that (bigger operation).

**Comment by ipentest** [comment]
OK cool thanks a lot for the note... Looking forward to the upgrade...
